-- Auto-generate certificate when course is completed (100% progress)
CREATE OR REPLACE FUNCTION check_and_generate_certificate()
RETURNS TRIGGER AS $$
DECLARE
  total_lessons integer;
  completed_lessons integer;
  course_record RECORD;
  student_record RECORD;
  template_record RECORD;
BEGIN
  -- Get enrollment details
  SELECT 
    ce.*,
    mc.title as course_title,
    mc.mentor_id,
    cm_student.full_name as student_name,
    cm_student.email as student_email
  INTO course_record
  FROM course_enrollments ce
  JOIN mentor_courses mc ON ce.course_id = mc.id
  JOIN community_members cm_student ON ce.student_id = cm_student.id
  WHERE ce.id = NEW.enrollment_id;

  IF NOT FOUND THEN
    RETURN NEW;
  END IF;

  -- Only proceed if progress is 100%
  IF NEW.progress_percentage < 100 THEN
    RETURN NEW;
  END IF;

  -- Check if certificate already exists
  IF EXISTS (
    SELECT 1 FROM course_certificates
    WHERE enrollment_id = NEW.id
    AND status = 'issued'
  ) THEN
    RETURN NEW;
  END IF;

  -- Get certificate template for this course
  SELECT * INTO template_record
  FROM certificate_templates
  WHERE course_id = course_record.course_id
  AND is_active = true
  LIMIT 1;

  -- If no template exists, create a default one
  IF NOT FOUND THEN
    INSERT INTO certificate_templates (
      course_id,
      template_name,
      template_html,
      is_active
    ) VALUES (
      course_record.course_id,
      'Default Certificate',
      '<div style="text-align: center; padding: 40px; font-family: Arial, sans-serif;">
        <h1 style="font-size: 48px; margin-bottom: 20px;">Certificate of Completion</h1>
        <p style="font-size: 24px; margin: 40px 0;">This certifies that</p>
        <h2 style="font-size: 32px; margin: 20px 0; color: #1D3A6B;">{{student_name}}</h2>
        <p style="font-size: 20px; margin: 40px 0;">has successfully completed</p>
        <h3 style="font-size: 28px; margin: 20px 0; color: #1D3A6B;">{{course_title}}</h3>
        <p style="font-size: 16px; margin-top: 60px;">Issued on {{issue_date}}</p>
        <p style="font-size: 14px; margin-top: 40px; color: #666;">Certificate Number: {{certificate_number}}</p>
      </div>',
      true
    ) RETURNING * INTO template_record;
  END IF;

  -- Generate certificate
  INSERT INTO course_certificates (
    enrollment_id,
    course_id,
    student_id,
    template_id,
    certificate_number,
    issued_at,
    status
  ) VALUES (
    NEW.id,
    course_record.course_id,
    course_record.student_id,
    template_record.id,
    NULL, -- Will be auto-generated by trigger
    NOW(),
    'issued'
  );

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_check_course_completion ON course_enrollments;
CREATE TRIGGER trigger_check_course_completion
AFTER UPDATE OF progress_percentage ON course_enrollments
FOR EACH ROW
WHEN (NEW.progress_percentage = 100 AND OLD.progress_percentage < 100)
EXECUTE FUNCTION check_and_generate_certificate();

-- Add index for faster certificate lookups
CREATE INDEX IF NOT EXISTS idx_course_certificates_enrollment ON course_certificates(enrollment_id);
CREATE INDEX IF NOT EXISTS idx_course_certificates_student ON course_certificates(student_id);
CREATE INDEX IF NOT EXISTS idx_course_certificates_course ON course_certificates(course_id);

